### ISSUE TITLE
新）CI

### ISSUE THREAD

**Issue by sharin-sushi** [sharin-sushi/V-Kara-Lists#104]
GitHub ActionsのCI実装

go　https://github.com/sharin-sushi/0015Laboratory/issues/31

**Comment by sharin-sushi** [comment]
お試しでやったのと同じようにしたつもりなのにできてないんだが

今回の[コード](https://github.com/sharin-sushi/V-Kara-Lists/blob/develop/.github/workflows/go.yml)

![image](https://github.com/sharin-sushi/V-Kara-Lists/assets/127638412/9bcb1eaf-92f3-44bf-bdf7-5f4fe6234ce1)

そもそも起動すらしてないのかな。
```
on:
  push:
    branches: [ "main, develop" ]
  pull_request:
    branches: [ "main, develop" ]
```
ではdevelopブランチにプルリクしても起動しないの…？

mainにもプルリクしてみるか。
